### ISSUE TITLE
[BUG] The effort for tackle-testapp with openJDK17 target seems low

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/analyzer-lsp#511] opened 2024-02-19 15:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

main

### Priority

Major

### Current Behavior

Using Tackle-Testapp

Analysis configuration:
Analysis mode: Source code + dependencies
Targets: OpenJDK 17
scope: Application and all dependencies, including known Open Source libraries
No additional advanced options
![Screenshot from 2024-02-19 18-00-40](https://github.com/konveyor/analyzer-lsp/assets/87791967/82e58c24-918c-4677-88b3-8e282bddb9c1) 
![Screenshot from 2024-02-19 18-01-11](https://github.com/konveyor/analyzer-lsp/assets/87791967/d142a17e-4572-414d-a17e-97f734018ac3)

### How Reproducible

Always (Default)

### Environment

```markdown
- **Analyzer Image SHA** 
- **JDTLS  base image SHA**
- **Provider Settings JSON**
```

**Comment by pranavgaikwad** [comment] 2024-02-20 19:55
@kpunwatk Are you sure you used the exact same options in both analyses? I am unable to reproduce this with latest images 
![image](https://github.com/konveyor/analyzer-lsp/assets/9839757/a37f92e7-a7a2-479a-8496-38ac305b2576)

**Comment by pranavgaikwad** [comment] 2024-02-22 15:00
Closing as this is not reproducible. @kpunwatk Please feel free to re-open when you have a reproducer

**Closed by pranavgaikwad** 2024-02-22 15:00 UTC
Labels: kind/bug, priority/backlog, triage/accepted
