### ISSUE TITLE
Issue not found in internal dependency

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#319] opened 2023-09-08 09:01 UTC
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration: 
  - Source + Dependencies
  - cloud-readiness, linux
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

The _File system - Java IO_ issue present in the config-utils dependency from the tackle-testapp applications is not found during the analysis, even when it has been configured in source + dependencies mode and the issue is found in many other dependencies.

### How to reproduce

- Analyze tackle-testapp.
- Go to the _Issues_ view, Single application tab and filter by the tackle-testapp application.
- Click on the _File system - Java IO_ issue. 37 affected files are found.
![Screenshot from 2023-09-08 10-55-04](https://github.com/konveyor/analyzer-lsp/assets/15966456/3317b3ac-159c-40cc-a1fe-9028fee56646)
- Browse the list of affected files in the side drawer. config-utils-1.0.0.jar is not there.

### Expected result

The incident is found in the ApplicationConfiguration class from the config-utils dependency, as it was found when running a Windup analysis:

![Screenshot from 2023-09-08 10-58-30](https://github.com/konveyor/analyzer-lsp/assets/15966456/8bef2fb7-cf6d-43be-b741-5cbae8a0195a)

### Actual result

There are no incidents for that issue found in config-utils:

![Screenshot from 2023-09-08 10-57-48](https://github.com/konveyor/analyzer-lsp/assets/15966456/060ccef9-f70b-4b91-ac64-b66d9f658415)

**Comment by pranavgaikwad** [comment] 2023-09-13 11:51
@rromannissen This is an interesting one. What is happening is that since filtering of open source deps wasn't working as expected in this image, we get all issues and then the first 1500 of them are added to output. So the internal dep ones are getting filtered-out. @shawn-hurley @fabianvf what do you guys think should happen here? I think this is expected behavior.

**Comment by shawn-hurley** [comment] 2023-09-13 17:14
Let's re-run this scenario with the deps filter working and make sure that it is still triggering.

I think that we if want to have some priority based on deps for the incidents that are included vs. excluded we will have to spend some time with that as a feature. I could see us moving this to a RFE, I don't think that we have time for future freeze to do the priority incidents based on dep labels

**Comment by pranavgaikwad** [comment] 2023-09-19 16:28
I apologize for the wrong root cause above. I am able to reproduce this issue now that the maven settings, the rulesets / labels are working as expected, it seems that the issue from this dep is not being matched in the first place. Speaking with @shawn-hurley on this more, it appears that we'er not getting a match because config-utils package doesn't have a sources Jar. To solve this, we will have to decompile the package using fernflower.

**Comment by rromannissen** [comment] 2023-09-29 10:54
Reproduced in 0.3-alpha5

**Closed** 2023-10-06 19:26 UTC
