### ISSUE TITLE
Placeholders in issue name and description are not being interpolated

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#328] opened 2023-09-11 16:15 UTC
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration:
  - Source + Dependencies
  - eap6
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

The {subpackage} placeholder in issue name and description is not being interpolated correctly.

### How to reproduce

- Analyze tackle-test app with the configuration available in the Environment section.
- Go to the issues view, Single application and filter by the tackle-testapp application.
- Select the _Apache org.apache.{subpackage} type reference_ issue.

### Expected result

Issue name should be should be  _Apache org.apache.activemq type reference_ 

### Actual result

Issue name is _Apache org.apache.{subpackage} type reference_ 

![Screenshot from 2023-09-11 18-14-47](https://github.com/konveyor/analyzer-lsp/assets/15966456/8ea30f62-7bac-40ca-bbdc-a42c1e747214)

Windup reports render this correctly for this match:

![Screenshot from 2023-09-11 18-02-17](https://github.com/konveyor/analyzer-lsp/assets/15966456/1aaf7432-01ac-4183-bb7d-f8f53fe5e545)

**Comment by shawn-hurley** [comment] 2023-09-13 18:16
I have seen quite a few rules have regex's that are failing and I am pretty sure that this is the cause.  @fabianvf mentioned adding a regex checker in the shim to validate them, and that will help us find *most* of these cases I think.

**Comment by pranavgaikwad** [comment] 2023-09-19 17:30
@shawn-hurley I agree to the regex part. But there are also occurrences where the matching is not working as expected. I found two problems:

* Sometimes there are multiple matches in code snip, and we only return the first one. For instance, in following code snip, if a rule has `referenced: jboss.seam.[A-Za-z]+` with a custom var `package` matching on `jboss.seam.(?P<package>[A-Za-z]+;)

```
1 import jboss.seam.Foo;
2 import jboss.seam.Bar;
```

We should get two incidents, with, package=Foo and package=Bar. In our case though, we do get two incidents with different line numbers `1` and `2` but in both of them we get `package=Foo`  because code snip has both lines and we only return first match.

* Sometimes we match on more stuff than needed. This is because the windup rules I think assume a line by line match, but since we do a match on multiple lines, we match on more stuff. This is a regex problem in the rule, but I'd still argue that we should do a match line by line to be more precise in our matching. 

To solve both the problems, we should match the custom vars on the line where incident is found instead of entire code snip. But I observed that in some cases we get the next line instead of the actual line in incidents. So a better approach would be to start matching from line number of the incident, if match is not found, traverse outside in both direction line by line doing a match to ensure we get the closest match to the line number.

**Comment by fabianvf** [comment] 2023-09-19 19:31
hmm

a) if we've got off-by-one issues we should probably fix those
b) I feel like we should only apply the regex to the matching line, not the surrounding context

**Comment by pranavgaikwad** [comment] 2023-09-19 19:43
@fabianvf Agreed, if incidents are off-by-one, we should def solve the underlying problem. I wasn't sure if there was a really problem there, because we have one occurrence in our demo [here](https://github.com/konveyor/analyzer-lsp/blob/b9bce95249f2778199517384b0dfbb36b2c7d2c7/demo-output.yaml#L250C6-L255C21) In the example above, line number should be 14. because rule is looking for method call.

**Comment by jmle** [comment] 2023-10-06 08:33
There is another side to this issue. In windup, for each parameter to be interpolated in a given rule (be it in the title or in the description), a different issue is created. See for instance the `javax-to-jakarta-import-00001` rule in konveyor vs windup:

In Konveyor, a single issue is created with _all possible parameters_:
![image](https://github.com/konveyor/analyzer-lsp/assets/4527008/2e131b3d-d978-46ca-af33-ecc486dd1047)

In Windup, multiple issue entries are created, one per parameter found:
![image](https://github.com/konveyor/analyzer-lsp/assets/4527008/2a06f271-2d92-45de-9246-75f13e0db452)
 
(CC @rromannissen )

**Comment by shawn-hurley** [comment] 2023-10-11 17:06
Yes, this is the correct behavior that we have agreed upon. We don't want to change this behavior IMO. 

Basically, the message should be for the specific instance, but the description should only contain info for the rule, not anything about particular cases of an issue. 

I hope that logic makes sense.

**Comment by pranavgaikwad** [comment] 2023-10-12 13:34
Okay I think we have decided that this is never going to get fixed, so closing this.

**Closed by pranavgaikwad** 2023-10-12 13:34 UTC
