### ISSUE TITLE
Missing dependencies after analysis

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#318] opened 2023-09-08 08:44 UTC
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration: 
  - Source + Dependencies
  - cloud-readiness, linux
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

After executing the analysis, most dependencies are missing in the _Dependencies_  view:
 
![Screenshot from 2023-09-08 10-22-04](https://github.com/konveyor/analyzer-lsp/assets/15966456/68d1951e-1b83-429f-a161-a7bf8744874d)

Only the direct internal dependency config-utils is being listed, when all dependencies, direct and transitive, should be listed for the application. For the tackle-testapp application the list of dependencies should be the following:

```
$ mvn dependency:list
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< io.konveyor.demo:customers-tomcat >------------------
[INFO] Building Order Management 0.0.1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:list (default-cli) @ customers-tomcat ---
[INFO] 
[INFO] The following files have been resolved:
[INFO]    org.springframework.boot:spring-boot-starter:jar:2.5.0:compile
[INFO]    org.springframework:spring-context:jar:5.3.7:compile
[INFO]    org.springframework:spring-core:jar:5.3.7:compile
[INFO]    org.springframework.boot:spring-boot-actuator:jar:2.5.0:compile
[INFO]    org.apache.tomcat:tomcat-juli:jar:9.0.46:runtime
[INFO]    javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO]    org.glassfish.jaxb:txw2:jar:2.3.1:compile
[INFO]    com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
[INFO]    org.springframework:spring-web:jar:5.3.7:compile
[INFO]    org.aspectj:aspectjrt:jar:1.9.6:compile
[INFO]    org.springframework.boot:spring-boot-starter-logging:jar:2.5.0:compile
[INFO]    org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO]    org.apache.tomcat:tomcat-jdbc:jar:9.0.46:runtime
[INFO]    org.springframework:spring-jcl:jar:5.3.7:compile
[INFO]    antlr:antlr:jar:2.7.7:compile
[INFO]    jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO]    io.micrometer:micrometer-core:jar:1.7.0:compile
[INFO]    org.springframework:spring-orm:jar:5.3.7:compile
[INFO]    org.springframework:spring-tx:jar:5.3.7:compile
[INFO]    org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO]    org.javassist:javassist:jar:3.27.0-GA:compile
[INFO]    com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO]    org.hibernate:hibernate-core:jar:5.4.32.Final:compile
[INFO]    org.postgresql:postgresql:jar:42.2.23:compile
[INFO]    org.dom4j:dom4j:jar:2.1.3:compile
[INFO]    org.springframework.boot:spring-boot-starter-actuator:jar:2.5.0:compile
[INFO]    org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.5.0:compile
[INFO]    javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO]    com.oracle.database.jdbc:ojdbc11:jar:21.1.0.0:compile
[INFO]    org.jvnet.staxex:stax-ex:jar:1.8:compile
[INFO]    org.springframework:spring-jdbc:jar:5.3.7:compile
[INFO]    org.apache.logging.log4j:log4j-to-slf4j:jar:2.14.1:compile
[INFO]    org.apache.tomcat:tomcat-servlet-api:jar:9.0.46:provided
[INFO]    org.yaml:snakeyaml:jar:1.28:compile
[INFO]    org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO]    com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
[INFO]    com.h2database:h2:jar:2.1.214:compile
[INFO]    com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO]    org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO]    org.springframework:spring-beans:jar:5.3.7:compile
[INFO]    org.hibernate:hibernate-entitymanager:jar:5.4.32.Final:compile
[INFO]    org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO]    org.springframework:spring-expression:jar:5.3.7:compile
[INFO]    org.checkerframework:checker-qual:jar:3.5.0:runtime
[INFO]    org.jboss:jandex:jar:2.2.3.Final:compile
[INFO]    org.springframework:spring-aop:jar:5.3.7:compile
[INFO]    com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.3:runtime
[INFO]    org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
[INFO]    org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO]    org.springframework.boot:spring-boot-autoconfigure:jar:2.5.0:compile
[INFO]    net.bytebuddy:byte-buddy:jar:1.10.22:compile
[INFO]    io.konveyor.demo:config-utils:jar:1.0.0:compile
[INFO]    org.springframework.data:spring-data-jpa:jar:2.5.1:compile
[INFO]    jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO]    org.apache.logging.log4j:log4j-api:jar:2.14.1:compile
[INFO]    org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO]    org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO]    ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO]    org.springframework.data:spring-data-commons:jar:2.5.1:compile
[INFO]    org.springframework:spring-webmvc:jar:5.3.7:compile
[INFO]    ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO]    javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO]    com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO]    com.fasterxml:classmate:jar:1.5.1:compile
[INFO]    org.springframework.boot:spring-boot:jar:2.5.0:compile
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.070 s
[INFO] Finished at: 2023-09-08T10:16:21+02:00
[INFO] ------------------------------------------------------------------------
```

Windup reports included all of these dependencies:

![Screenshot from 2023-09-08 10-39-45](https://github.com/konveyor/analyzer-lsp/assets/15966456/bce202e7-c1df-4b83-be61-9ea0f4fc3680)

### How to reproduce

- Analyze tackle-testapp
- Go to the _Dependencies_ view.
- Filter by the tackle-testapp application.

### Expected result

All dependencies for the tackle-testapp application are listed, including information about them being either direct or transitive in the dependency drawer.

### Actual result

Only the config-utils dependency is listed.

**Comment by pranavgaikwad** [comment] 2023-09-11 14:29
I am unable to reproduce this in my local analyzer environment (latest) as well as in the hub using the latest analyzer addon image. I believe this was some issue in either addon / hub in the images you used. I think this will be solved after rebuild too.

**Comment by pranavgaikwad** [comment] 2023-09-12 19:45
Okay, so I found the root cause for this. Earlier I was unable to reproduce this issue in latest because maven index file was busted and that caused all deps to get filtered-in (none had labels because of empty maven file). Now that the maven index is fixed in latest, you can reproduce this with latest too.

The real issue here is that the addon is passing `--dep-label-selector` to the dependency generation CLI and not the analysis CLI. We want to exclude incidents that come from open-source dependencies, not the dependencies themselves.

**Comment by pranavgaikwad** [comment] 2023-09-13 11:47
Should be fixed via PR Jeff linked above, will close after giving it a test.

**Comment by pranavgaikwad** [comment] 2023-09-19 16:29
Closing as I tested that this is working as expected now as long as you pass the maven settings file.

**Closed by pranavgaikwad** 2023-09-19 16:29 UTC
